# Generated by Django 3.0.5 on 2020-04-25 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('min_price', models.PositiveIntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.RoomCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(auto_created=True, default=False)),
                ('confirmation_number', models.TextField(validators=[django.core.validators.RegexValidator('[0-9]{8}')])),
                ('date_check_in', models.DateTimeField()),
                ('date_check_out', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.Room')),
            ],
        ),
    ]
