# Generated by Django 3.0.5 on 2020-04-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_booking_hotelinfo_room_roomcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomcategory',
            options={'verbose_name_plural': 'Room categories'},
        ),
        migrations.AddField(
            model_name='user',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='back.Hotel'),
        ),
    ]
