# Generated by Django 3.0.5 on 2020-04-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20200425_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
