# Generated by Django 3.0.5 on 2020-04-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_auto_20200426_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='active',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
