# Generated by Django 3.0.5 on 2020-04-26 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_auto_20200426_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='confirmation_number',
            field=models.CharField(max_length=8, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
