# Generated by Django 3.0.5 on 2020-04-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_auto_20200426_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.Booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.User')),
            ],
        ),
    ]
