# Generated by Django 3.0.5 on 2020-04-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(auto_created=True, default=None),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='message_id',
            field=models.IntegerField(auto_created=True, default=None),
        ),
    ]
