# Generated by Django 3.0.5 on 2020-04-26 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_auto_20200426_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.Booking'),
        ),
    ]
